"""forum_refactor_and_reports

Revision ID: 035600396283
Revises: a07bd1037c4d
Create Date: 2026-04-24 19:18:10.514990
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Alembic revision tanımlayıcıları
revision: str = '035600396283'
down_revision: Union[str, Sequence[str], None] = 'a07bd1037c4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Veritabanı şemasını yükselt."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forum_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=True),
    sa.Column('reply_id', sa.String(length=36), nullable=True),
    sa.Column('reporter_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['reply_id'], ['forum_replies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['forum_topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forum_reports_reply_id'), 'forum_reports', ['reply_id'], unique=False)
    op.create_index(op.f('ix_forum_reports_reporter_id'), 'forum_reports', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_forum_reports_topic_id'), 'forum_reports', ['topic_id'], unique=False)
    op.add_column('forum_categories', sa.Column('university_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_forum_categories_university_id'), 'forum_categories', ['university_id'], unique=False)
    op.create_foreign_key(None, 'forum_categories', 'universities', ['university_id'], ['id'])
    op.add_column('forum_topics', sa.Column('university_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_forum_topics_university_id'), 'forum_topics', ['university_id'], unique=False)
    op.create_foreign_key(None, 'forum_topics', 'universities', ['university_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Veritabanı şemasını geri al."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'forum_topics', type_='foreignkey')
    op.drop_index(op.f('ix_forum_topics_university_id'), table_name='forum_topics')
    op.drop_column('forum_topics', 'university_id')
    op.drop_constraint(None, 'forum_categories', type_='foreignkey')
    op.drop_index(op.f('ix_forum_categories_university_id'), table_name='forum_categories')
    op.drop_column('forum_categories', 'university_id')
    op.drop_index(op.f('ix_forum_reports_topic_id'), table_name='forum_reports')
    op.drop_index(op.f('ix_forum_reports_reporter_id'), table_name='forum_reports')
    op.drop_index(op.f('ix_forum_reports_reply_id'), table_name='forum_reports')
    op.drop_table('forum_reports')
    # ### end Alembic commands ###
