"""initial_schema_clean

Revision ID: 0ea4742e0b4e
Revises: 
Create Date: 2026-02-15 19:56:06.588331
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Alembic revision tanımlayıcıları
revision: str = '0ea4742e0b4e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Veritabanı şemasını yükselt."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forum_categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('order_index', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('universities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('university_type', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('email_domains', sa.Text(), nullable=True),
    sa.Column('yok_data', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_university_name_type', 'universities', ['name', 'university_type'], unique=False)
    op.create_index(op.f('ix_universities_city'), 'universities', ['city'], unique=False)
    op.create_index(op.f('ix_universities_is_active'), 'universities', ['is_active'], unique=False)
    op.create_index(op.f('ix_universities_name'), 'universities', ['name'], unique=False)
    op.create_index(op.f('ix_universities_university_type'), 'universities', ['university_type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('username_last_changed_at', sa.DateTime(), nullable=True),
    sa.Column('university', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('student', 'instructor', 'admin', name='userrole', native_enum=False), nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('profile_picture_url', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('theme_preference', sa.String(length=10), server_default=sa.text("'light'"), nullable=False),
    sa.Column('terms_accepted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_is_verified'), 'users', ['is_verified'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('academic_calendar_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('university', sa.String(length=255), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_calendar_events_university'), 'academic_calendar_events', ['university'], unique=False)
    op.create_table('academic_contributions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('university', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('class_year', sa.String(length=50), nullable=True),
    sa.Column('semester', sa.String(length=20), nullable=True),
    sa.Column('academic_year', sa.String(length=20), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('manual_data', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_contributions_status'), 'academic_contributions', ['status'], unique=False)
    op.create_index(op.f('ix_academic_contributions_type'), 'academic_contributions', ['type'], unique=False)
    op.create_index(op.f('ix_academic_contributions_user_id'), 'academic_contributions', ['user_id'], unique=False)
    op.create_table('ai_conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_conversations_user_id'), 'ai_conversations', ['user_id'], unique=False)
    op.create_table('ai_knowledge_base',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_knowledge_base_is_active'), 'ai_knowledge_base', ['is_active'], unique=False)
    op.create_index(op.f('ix_ai_knowledge_base_priority'), 'ai_knowledge_base', ['priority'], unique=False)
    op.create_table('ai_system_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('rate_limit_per_day', sa.Integer(), server_default=sa.text('50'), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('career_listings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('posted_by', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('is_remote', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('application_type', sa.String(length=20), nullable=False),
    sa.Column('external_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('view_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('application_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['posted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_listings_created_at'), 'career_listings', ['created_at'], unique=False)
    op.create_index(op.f('ix_career_listings_posted_by'), 'career_listings', ['posted_by'], unique=False)
    op.create_index(op.f('ix_career_listings_status'), 'career_listings', ['status'], unique=False)
    op.create_index(op.f('ix_career_listings_type'), 'career_listings', ['type'], unique=False)
    op.create_table('contact_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.Column('answered_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['answered_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_messages_created_at'), 'contact_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_contact_messages_status'), 'contact_messages', ['status'], unique=False)
    op.create_index(op.f('ix_contact_messages_user_id'), 'contact_messages', ['user_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('reference_id', sa.String(length=36), nullable=False),
    sa.Column('user1_id', sa.String(length=36), nullable=False),
    sa.Column('user2_id', sa.String(length=36), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('user1_unread_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('user2_unread_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user2_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'reference_id', 'user1_id', 'user2_id', name='uq_conversations_unique')
    )
    op.create_index(op.f('ix_conversations_last_message_at'), 'conversations', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_conversations_user1_id'), 'conversations', ['user1_id'], unique=False)
    op.create_index(op.f('ix_conversations_user2_id'), 'conversations', ['user2_id'], unique=False)
    op.create_table('course_schedules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('university', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('class_year', sa.String(length=50), nullable=False),
    sa.Column('semester', sa.String(length=20), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('schedule_data', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('university', 'department', 'class_year', 'semester', 'academic_year', name='uq_course_schedules_unique')
    )
    op.create_index(op.f('ix_course_schedules_department'), 'course_schedules', ['department'], unique=False)
    op.create_index(op.f('ix_course_schedules_university'), 'course_schedules', ['university'], unique=False)
    op.create_table('forum_topics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('view_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('reply_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('helpful_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_reply_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['forum_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forum_topics_author_id'), 'forum_topics', ['author_id'], unique=False)
    op.create_index(op.f('ix_forum_topics_category_id'), 'forum_topics', ['category_id'], unique=False)
    op.create_index(op.f('ix_forum_topics_created_at'), 'forum_topics', ['created_at'], unique=False)
    op.create_table('marketplace_listings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('seller_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('condition', sa.String(length=50), nullable=False),
    sa.Column('image_urls', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('view_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('message_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_listings_category'), 'marketplace_listings', ['category'], unique=False)
    op.create_index(op.f('ix_marketplace_listings_created_at'), 'marketplace_listings', ['created_at'], unique=False)
    op.create_index(op.f('ix_marketplace_listings_seller_id'), 'marketplace_listings', ['seller_id'], unique=False)
    op.create_index(op.f('ix_marketplace_listings_status'), 'marketplace_listings', ['status'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('ai_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_messages_conversation_id'), 'ai_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ai_messages_created_at'), 'ai_messages', ['created_at'], unique=False)
    op.create_table('career_applications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('listing_id', sa.String(length=36), nullable=False),
    sa.Column('applicant_id', sa.String(length=36), nullable=False),
    sa.Column('application_type', sa.String(length=20), nullable=False),
    sa.Column('dm_conversation_id', sa.String(length=36), nullable=True),
    sa.Column('applied_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dm_conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['career_listings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id', 'applicant_id', name='uq_career_applications_listing_applicant')
    )
    op.create_index(op.f('ix_career_applications_applicant_id'), 'career_applications', ['applicant_id'], unique=False)
    op.create_index(op.f('ix_career_applications_listing_id'), 'career_applications', ['listing_id'], unique=False)
    op.create_table('career_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('sender_id', sa.String(length=36), nullable=False),
    sa.Column('receiver_id', sa.String(length=36), nullable=False),
    sa.Column('listing_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['career_listings.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_messages_conversation_id'), 'career_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_career_messages_created_at'), 'career_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_career_messages_listing_id'), 'career_messages', ['listing_id'], unique=False)
    op.create_index(op.f('ix_career_messages_receiver_id'), 'career_messages', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_career_messages_sender_id'), 'career_messages', ['sender_id'], unique=False)
    op.create_table('career_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('listing_id', sa.String(length=36), nullable=False),
    sa.Column('reporter_user_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['career_listings.id'], ),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forum_replies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('helpful_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['forum_topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forum_replies_author_id'), 'forum_replies', ['author_id'], unique=False)
    op.create_index(op.f('ix_forum_replies_created_at'), 'forum_replies', ['created_at'], unique=False)
    op.create_index(op.f('ix_forum_replies_topic_id'), 'forum_replies', ['topic_id'], unique=False)
    op.create_table('marketplace_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('sender_id', sa.String(length=36), nullable=False),
    sa.Column('receiver_id', sa.String(length=36), nullable=False),
    sa.Column('listing_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['marketplace_listings.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_messages_conversation_id'), 'marketplace_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_marketplace_messages_created_at'), 'marketplace_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_marketplace_messages_listing_id'), 'marketplace_messages', ['listing_id'], unique=False)
    op.create_index(op.f('ix_marketplace_messages_receiver_id'), 'marketplace_messages', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_marketplace_messages_sender_id'), 'marketplace_messages', ['sender_id'], unique=False)
    op.create_table('marketplace_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('listing_id', sa.String(length=36), nullable=False),
    sa.Column('reporter_user_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['marketplace_listings.id'], ),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Veritabanı şemasını geri al."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marketplace_reports')
    op.drop_index(op.f('ix_marketplace_messages_sender_id'), table_name='marketplace_messages')
    op.drop_index(op.f('ix_marketplace_messages_receiver_id'), table_name='marketplace_messages')
    op.drop_index(op.f('ix_marketplace_messages_listing_id'), table_name='marketplace_messages')
    op.drop_index(op.f('ix_marketplace_messages_created_at'), table_name='marketplace_messages')
    op.drop_index(op.f('ix_marketplace_messages_conversation_id'), table_name='marketplace_messages')
    op.drop_table('marketplace_messages')
    op.drop_index(op.f('ix_forum_replies_topic_id'), table_name='forum_replies')
    op.drop_index(op.f('ix_forum_replies_created_at'), table_name='forum_replies')
    op.drop_index(op.f('ix_forum_replies_author_id'), table_name='forum_replies')
    op.drop_table('forum_replies')
    op.drop_table('career_reports')
    op.drop_index(op.f('ix_career_messages_sender_id'), table_name='career_messages')
    op.drop_index(op.f('ix_career_messages_receiver_id'), table_name='career_messages')
    op.drop_index(op.f('ix_career_messages_listing_id'), table_name='career_messages')
    op.drop_index(op.f('ix_career_messages_created_at'), table_name='career_messages')
    op.drop_index(op.f('ix_career_messages_conversation_id'), table_name='career_messages')
    op.drop_table('career_messages')
    op.drop_index(op.f('ix_career_applications_listing_id'), table_name='career_applications')
    op.drop_index(op.f('ix_career_applications_applicant_id'), table_name='career_applications')
    op.drop_table('career_applications')
    op.drop_index(op.f('ix_ai_messages_created_at'), table_name='ai_messages')
    op.drop_index(op.f('ix_ai_messages_conversation_id'), table_name='ai_messages')
    op.drop_table('ai_messages')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_marketplace_listings_status'), table_name='marketplace_listings')
    op.drop_index(op.f('ix_marketplace_listings_seller_id'), table_name='marketplace_listings')
    op.drop_index(op.f('ix_marketplace_listings_created_at'), table_name='marketplace_listings')
    op.drop_index(op.f('ix_marketplace_listings_category'), table_name='marketplace_listings')
    op.drop_table('marketplace_listings')
    op.drop_index(op.f('ix_forum_topics_created_at'), table_name='forum_topics')
    op.drop_index(op.f('ix_forum_topics_category_id'), table_name='forum_topics')
    op.drop_index(op.f('ix_forum_topics_author_id'), table_name='forum_topics')
    op.drop_table('forum_topics')
    op.drop_index(op.f('ix_course_schedules_university'), table_name='course_schedules')
    op.drop_index(op.f('ix_course_schedules_department'), table_name='course_schedules')
    op.drop_table('course_schedules')
    op.drop_index(op.f('ix_conversations_user2_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_user1_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_last_message_at'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_contact_messages_user_id'), table_name='contact_messages')
    op.drop_index(op.f('ix_contact_messages_status'), table_name='contact_messages')
    op.drop_index(op.f('ix_contact_messages_created_at'), table_name='contact_messages')
    op.drop_table('contact_messages')
    op.drop_index(op.f('ix_career_listings_type'), table_name='career_listings')
    op.drop_index(op.f('ix_career_listings_status'), table_name='career_listings')
    op.drop_index(op.f('ix_career_listings_posted_by'), table_name='career_listings')
    op.drop_index(op.f('ix_career_listings_created_at'), table_name='career_listings')
    op.drop_table('career_listings')
    op.drop_table('ai_system_settings')
    op.drop_index(op.f('ix_ai_knowledge_base_priority'), table_name='ai_knowledge_base')
    op.drop_index(op.f('ix_ai_knowledge_base_is_active'), table_name='ai_knowledge_base')
    op.drop_table('ai_knowledge_base')
    op.drop_index(op.f('ix_ai_conversations_user_id'), table_name='ai_conversations')
    op.drop_table('ai_conversations')
    op.drop_index(op.f('ix_academic_contributions_user_id'), table_name='academic_contributions')
    op.drop_index(op.f('ix_academic_contributions_type'), table_name='academic_contributions')
    op.drop_index(op.f('ix_academic_contributions_status'), table_name='academic_contributions')
    op.drop_table('academic_contributions')
    op.drop_index(op.f('ix_academic_calendar_events_university'), table_name='academic_calendar_events')
    op.drop_table('academic_calendar_events')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_verified'), table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_universities_university_type'), table_name='universities')
    op.drop_index(op.f('ix_universities_name'), table_name='universities')
    op.drop_index(op.f('ix_universities_is_active'), table_name='universities')
    op.drop_index(op.f('ix_universities_city'), table_name='universities')
    op.drop_index('idx_university_name_type', table_name='universities')
    op.drop_table('universities')
    op.drop_table('forum_categories')
    # ### end Alembic commands ###
