"""add_references_to_ai_messages

Revision ID: 41860df6309b
Revises: 439287a4cdd6
Create Date: 2026-05-15 20:58:02.188963
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Alembic revision tanımlayıcıları
revision: str = '41860df6309b'
down_revision: Union[str, Sequence[str], None] = '439287a4cdd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Veritabanı şemasını yükselt."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_messages', sa.Column('references', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Veritabanı şemasını geri al."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_messages', 'references')
    # ### end Alembic commands ###
