"""Add is_private to users

Revision ID: 439287a4cdd6
Revises: 2472b48c3674
Create Date: 2026-05-15 16:38:18.406096
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Alembic revision tanımlayıcıları
revision: str = '439287a4cdd6'
down_revision: Union[str, Sequence[str], None] = '2472b48c3674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Veritabanı şemasını yükselt."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_private', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Veritabanı şemasını geri al."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_private')
    # ### end Alembic commands ###
