"""add_title_to_ai_conversations

Revision ID: 51113c9abd6e
Revises: 41860df6309b
Create Date: 2026-05-15 21:11:32.942334
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Alembic revision tanımlayıcıları
revision: str = '51113c9abd6e'
down_revision: Union[str, Sequence[str], None] = '41860df6309b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Veritabanı şemasını yükselt."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_conversations', sa.Column('title', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Veritabanı şemasını geri al."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_conversations', 'title')
    # ### end Alembic commands ###
