"""add_marketplace_categories

Revision ID: 560f8392dfff
Revises: b3f2a1c8d9e0
Create Date: 2026-05-03 20:12:04.292516
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Alembic revision tanımlayıcıları
revision: str = '560f8392dfff'
down_revision: Union[str, Sequence[str], None] = 'b3f2a1c8d9e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Veritabanı şemasını yükselt."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('marketplace_categories_university_id_fkey'), 'marketplace_categories', type_='foreignkey')
    op.create_foreign_key(None, 'marketplace_categories', 'universities', ['university_id'], ['id'])
    op.drop_constraint(op.f('fk_marketplace_listings_category_id'), 'marketplace_listings', type_='foreignkey')
    op.create_foreign_key(None, 'marketplace_listings', 'marketplace_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Veritabanı şemasını geri al."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'marketplace_listings', type_='foreignkey')
    op.create_foreign_key(op.f('fk_marketplace_listings_category_id'), 'marketplace_listings', 'marketplace_categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'marketplace_categories', type_='foreignkey')
    op.create_foreign_key(op.f('marketplace_categories_university_id_fkey'), 'marketplace_categories', 'universities', ['university_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
