"""add_department_table_and_user_relation

Revision ID: 715706673a06
Revises: 0ea4742e0b4e
Create Date: 2026-02-15 20:47:14.015418
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Alembic revision tanımlayıcıları
revision: str = '715706673a06'
down_revision: Union[str, Sequence[str], None] = '0ea4742e0b4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Veritabanı şemasını yükselt."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    op.add_column('users', sa.Column('department_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'departments', ['department_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('users', 'department')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Veritabanı şemasını geri al."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('department', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'department_id')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
