"""add_university_id_to_listings

Revision ID: 77dd368ae4cc
Revises: 51113c9abd6e
Create Date: 2026-05-16 21:44:15.575270
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Alembic revision tanımlayıcıları
revision: str = '77dd368ae4cc'
down_revision: Union[str, Sequence[str], None] = '51113c9abd6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Veritabanı şemasını yükselt."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('career_listings', sa.Column('university_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_career_listings_university_id'), 'career_listings', ['university_id'], unique=False)
    op.create_foreign_key(None, 'career_listings', 'universities', ['university_id'], ['id'], ondelete='SET NULL')
    op.add_column('marketplace_listings', sa.Column('university_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_marketplace_listings_university_id'), 'marketplace_listings', ['university_id'], unique=False)
    op.create_foreign_key(None, 'marketplace_listings', 'universities', ['university_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Veritabanı şemasını geri al."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'marketplace_listings', type_='foreignkey')
    op.drop_index(op.f('ix_marketplace_listings_university_id'), table_name='marketplace_listings')
    op.drop_column('marketplace_listings', 'university_id')
    op.drop_constraint(None, 'career_listings', type_='foreignkey')
    op.drop_index(op.f('ix_career_listings_university_id'), table_name='career_listings')
    op.drop_column('career_listings', 'university_id')
    # ### end Alembic commands ###
