"""add_university_id_to_knowledge_base

Revision ID: 9917853fb423
Revises: 560f8392dfff
Create Date: 2026-05-07 17:53:16.517146
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Alembic revision tanımlayıcıları
revision: str = '9917853fb423'
down_revision: Union[str, Sequence[str], None] = '560f8392dfff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Veritabanı şemasını yükselt."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_knowledge_base', sa.Column('university_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_ai_knowledge_base_university_id'), 'ai_knowledge_base', ['university_id'], unique=False)
    op.create_foreign_key(None, 'ai_knowledge_base', 'universities', ['university_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Veritabanı şemasını geri al."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ai_knowledge_base', type_='foreignkey')
    op.drop_index(op.f('ix_ai_knowledge_base_university_id'), table_name='ai_knowledge_base')
    op.drop_column('ai_knowledge_base', 'university_id')
    # ### end Alembic commands ###
