"""add_personal_schedule

Revision ID: ac1c0b340e50
Revises: 035600396283
Create Date: 2026-05-02 12:01:06.247844
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from src.models.base import DialectJSON


# Alembic revision tanımlayıcıları
revision: str = 'ac1c0b340e50'
down_revision: Union[str, Sequence[str], None] = '035600396283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Veritabanı şemasını yükselt."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_schedules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('base_schedule_id', sa.String(length=36), nullable=True),
    sa.Column('schedule_data', DialectJSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['base_schedule_id'], ['course_schedules.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_schedules_user_id'), 'personal_schedules', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Veritabanı şemasını geri al."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_personal_schedules_user_id'), table_name='personal_schedules')
    op.drop_table('personal_schedules')
    # ### end Alembic commands ###
