
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Alembic revision tanımlayıcıları
revision: str = 'e09e6c4bbc41'
down_revision: Union[str, Sequence[str], None] = '9c2b7f3a1d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Veritabanı şemasını yükselt."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forum_poll_options',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('option_text', sa.String(length=255), nullable=False),
    sa.Column('vote_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['forum_topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forum_poll_options_topic_id'), 'forum_poll_options', ['topic_id'], unique=False)
    op.create_table('forum_poll_votes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('poll_option_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['poll_option_id'], ['forum_poll_options.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forum_poll_votes_poll_option_id'), 'forum_poll_votes', ['poll_option_id'], unique=False)
    op.create_index(op.f('ix_forum_poll_votes_user_id'), 'forum_poll_votes', ['user_id'], unique=False)
    op.add_column('forum_replies', sa.Column('parent_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_forum_replies_parent_id'), 'forum_replies', ['parent_id'], unique=False)
    op.create_foreign_key(None, 'forum_replies', 'forum_replies', ['parent_id'], ['id'], ondelete='CASCADE')
    op.add_column('forum_topics', sa.Column('topic_type', sa.String(length=20), server_default=sa.text("'text'"), nullable=False))
    op.alter_column('forum_topics', 'category_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('forum_topics', 'tags',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('forum_topics', 'image_urls',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_column('forum_topics', 'event_location')
    op.drop_column('forum_topics', 'event_date')
    op.drop_column('forum_topics', 'post_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Veritabanı şemasını geri al."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forum_topics', sa.Column('post_type', sa.VARCHAR(length=50), server_default=sa.text("'text'::character varying"), autoincrement=False, nullable=False))
    op.add_column('forum_topics', sa.Column('event_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('forum_topics', sa.Column('event_location', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('forum_topics', 'image_urls',
               existing_type=sa.Text(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('forum_topics', 'tags',
               existing_type=sa.Text(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('forum_topics', 'category_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_column('forum_topics', 'topic_type')
    op.drop_constraint(None, 'forum_replies', type_='foreignkey')
    op.drop_index(op.f('ix_forum_replies_parent_id'), table_name='forum_replies')
    op.drop_column('forum_replies', 'parent_id')
    op.drop_index(op.f('ix_forum_poll_votes_user_id'), table_name='forum_poll_votes')
    op.drop_index(op.f('ix_forum_poll_votes_poll_option_id'), table_name='forum_poll_votes')
    op.drop_table('forum_poll_votes')
    op.drop_index(op.f('ix_forum_poll_options_topic_id'), table_name='forum_poll_options')
    op.drop_table('forum_poll_options')
    # ### end Alembic commands ###
