"""remove_redundant_university_string

Revision ID: e4cc129e427d
Revises: e8f05699052c
Create Date: 2026-04-22 21:33:07.157016
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Alembic revision tanımlayıcıları
revision: str = 'e4cc129e427d'
down_revision: Union[str, Sequence[str], None] = 'e8f05699052c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Veritabanı şemasını yükselt."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_calendar_events', schema=None) as batch_op:
        # SQLite batch kopyalama sırasında stale index referansını önlemek için önce index'i düşür
        batch_op.drop_index('ix_academic_calendar_events_university')
        batch_op.drop_column('university')

    with op.batch_alter_table('course_schedules', schema=None) as batch_op:
        # Aynı nedenle university kolonuna bağlı eski index'i önce kaldır
        batch_op.drop_index('ix_course_schedules_university')
        batch_op.drop_column('university')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Veritabanı şemasını geri al."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('university', sa.VARCHAR(length=255), nullable=False))

    with op.batch_alter_table('academic_calendar_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('university', sa.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
