"""add_course_notes_module

Revision ID: e8f05699052c
Revises: c6bb29278663
Create Date: 2026-04-22 20:34:08.571057
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Alembic revision tanımlayıcıları
revision: str = 'e8f05699052c'
down_revision: Union[str, Sequence[str], None] = 'c6bb29278663'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Veritabanı şemasını yükselt."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_note_topics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('course_code', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('university_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_course_note_topics_created_by', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], name='fk_course_note_topics_university_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course_note_topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_note_topics_course_code'), ['course_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_note_topics_university_id'), ['university_id'], unique=False)

    op.create_table('course_note_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['course_note_topics.id'], name='fk_course_note_entries_topic_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_course_note_entries_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course_note_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_note_entries_topic_id'), ['topic_id'], unique=False)

    op.create_table('course_note_attachments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entry_id', sa.String(length=36), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['course_note_entries.id'], name='fk_course_note_attachments_entry_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course_note_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_note_attachments_entry_id'), ['entry_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Veritabanı şemasını geri al."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_note_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_note_attachments_entry_id'))

    op.drop_table('course_note_attachments')
    with op.batch_alter_table('course_note_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_note_entries_topic_id'))

    op.drop_table('course_note_entries')
    with op.batch_alter_table('course_note_topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_note_topics_university_id'))
        batch_op.drop_index(batch_op.f('ix_course_note_topics_course_code'))

    op.drop_table('course_note_topics')
    # ### end Alembic commands ###
