"""add_user_favorites

Revision ID: ec83406d5d74
Revises: 359bba3ea951
Create Date: 2026-02-27 23:28:39.529410
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Alembic revision tanımlayıcıları
revision: str = 'ec83406d5d74'
down_revision: Union[str, Sequence[str], None] = '359bba3ea951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Veritabanı şemasını yükselt."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_favorites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_favorites_target_id'), 'user_favorites', ['target_id'], unique=False)
    op.create_index(op.f('ix_user_favorites_target_type'), 'user_favorites', ['target_type'], unique=False)
    op.create_index(op.f('ix_user_favorites_user_id'), 'user_favorites', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Veritabanı şemasını geri al."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_favorites_user_id'), table_name='user_favorites')
    op.drop_index(op.f('ix_user_favorites_target_type'), table_name='user_favorites')
    op.drop_index(op.f('ix_user_favorites_target_id'), table_name='user_favorites')
    op.drop_table('user_favorites')
    # ### end Alembic commands ###
